import { LegalPageLayout } from '@/components/layout/LegalPageLayout'
import { Link } from 'react-router-dom'

export function PrivacyPage() {
  return (
    <LegalPageLayout pageTitle="Privacy Policy" lastUpdated="March 2024">
      <h2>1. Information We Collect</h2>
      <p>
        When you use Torch Studio, we collect information you provide directly and information generated by your use of the Service.
      </p>
      <p><strong>Information you provide:</strong></p>
      <ul>
        <li><strong>Account information:</strong> Your name and email address when you create an account.</li>
        <li><strong>Payment information:</strong> Payment details are processed by Stripe and are not stored on our servers. We receive only a transaction confirmation and the last four digits of your payment method.</li>
        <li><strong>Communications:</strong> Messages you send to our support team via the contact form.</li>
      </ul>
      <p><strong>Information we collect automatically:</strong></p>
      <ul>
        <li><strong>Usage data:</strong> Pages visited, tracks previewed, downloads initiated, search queries, and time spent on the platform.</li>
        <li><strong>Device and browser information:</strong> Browser type, operating system, IP address, and device identifiers.</li>
        <li><strong>Cookies:</strong> See our <Link to="/legal/cookies" className="text-primary hover:underline">Cookie Policy</Link> for details.</li>
      </ul>

      <h2>2. How We Use Your Information</h2>
      <p>We use the information we collect to:</p>
      <ul>
        <li>Provide, maintain, and improve the Service.</li>
        <li>Process transactions and send related information, including purchase confirmations and receipts.</li>
        <li>Send you technical notices, security alerts, and support messages.</li>
        <li>Respond to your comments and questions.</li>
        <li>Analyze usage patterns to improve the catalog and user experience.</li>
        <li>Detect and prevent fraudulent transactions and other abuse of the Service.</li>
      </ul>
      <p>We do not sell your personal information to third parties.</p>

      <h2>3. Cookies</h2>
      <p>
        We use cookies and similar tracking technologies to operate the Service. For a detailed breakdown of the cookies we use and how to manage them, please see our <Link to="/legal/cookies" className="text-primary hover:underline">Cookie Policy</Link>.
      </p>

      <h2>4. Third-Party Services</h2>
      <p>We use the following third-party services that may process your data:</p>
      <ul>
        <li><strong>Stripe:</strong> Payment processing. Subject to <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Stripe's Privacy Policy</a>.</li>
        <li><strong>Analytics providers:</strong> We use privacy-respecting analytics to understand how the Service is used. Data is aggregated and anonymized where possible.</li>
      </ul>

      <h2>5. Data Retention</h2>
      <p>
        We retain your account information for as long as your account is active or as needed to provide you services. Download history is retained for 12 months to support re-download access. You may request deletion of your account and associated data at any time from your account settings.
      </p>

      <h2>6. Your Rights</h2>
      <p>
        Depending on your location, you may have the following rights regarding your personal data:
      </p>
      <ul>
        <li><strong>Access:</strong> Request a copy of the personal data we hold about you.</li>
        <li><strong>Correction:</strong> Request correction of inaccurate or incomplete data.</li>
        <li><strong>Deletion:</strong> Request deletion of your personal data (subject to certain legal obligations).</li>
        <li><strong>Portability:</strong> Request transfer of your data in a machine-readable format (GDPR).</li>
        <li><strong>Opt-out of sale:</strong> We do not sell personal data. California residents may exercise CCPA rights by contacting us.</li>
      </ul>
      <p>
        To exercise any of these rights, please <Link to="/support/contact" className="text-primary hover:underline">contact us</Link>.
      </p>

      <h2>7. Contact Us</h2>
      <p>
        If you have questions about this Privacy Policy or how we handle your data, please <Link to="/support/contact" className="text-primary hover:underline">contact our support team</Link>. We aim to respond within 2 business days.
      </p>
    </LegalPageLayout>
  )
}
